name: 새로운 프로젝트 등록
description: 무덤에 새로운 프로젝트를 등록합니다
title: "feat: [프로젝트명] 프로젝트 등록"
body:
  - type: input
    attributes:
      label: 프로젝트명
      required: true
  - type: input
    attributes:
      label: 개발 기간
      description: "예: 2023.08 - 2023.10"
      required: true
  - type: input
    attributes:
      label: 기술 스택
      description: "사용된 기술들을 쉼표로 구분해 입력해주세요. 예: Python, Flask, React, OpenAI API"
      required: true
  - type: textarea
    attributes:
      label: 중단 사유
      required: false
  - type: textarea
    attributes:
      label: 배운 점
      required: false
  - type: input
    attributes:
      label: GitHub 저장소
      required: false
  - type: input
    attributes:
      label: 작성자
      required: true
